In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
df = pd.read_csv('train_split_Depression_AVEC2017.csv', delimiter = ',')
df.head(50)

Participant_ID  PHQ8_Binary  PHQ8_Score  Gender  PHQ8_NoInterest  \
0              303            0           0       0                0   
1              304            0           6       0                0   
2              305            0           7       1                0   
3              310            0           4       1                1   
4              312            0           2       1                0   
5              313            0           7       1                1   
6              315            0           2       1                0   
7              316            0           6       1                1   
8              317            0           8       1                1   
9              318            0           3       1                0   
10             319            1          13       1                2   
11             320            1          11       0                1   
12             321            1          20       0                2   
13             322            0           5       1                1   
14             324            0           5       1                1   
15             325            1          10       0                1   
16             326            0           2       1                0   
17             327            0           4       0                0   
18             328            0           4       1                0   
19             330            1          12       1                1   
20             333            0           5       1                1   
21             336            0           7       1                0   
22             338            1          15       0                2   
23             339            1          11       1                1   
24             340            0           1       1                0   
25             341            0           7       0                2   
26             343            0           9       1                1   
27             344            1          11       1                1   
28             345            1          15       0                2   
29             347            1          16       1                3   
30             348            1          20       0                3   
31             350            1          11       0                1   
32             351            1          14       0                2   
33             352            1          10       0                1   
34             353            1          11       0                1   
35             355            1          10       1                1   
36             356            1          10       1                1   
37             357            0           7       1                1   
38             358            0           7       1                0   
39             360            0           4       0                1   
40             362            1          20       0                2   
41             363            0           0       1                0   
42             364            0           0       1                0   
43             366            0           0       1                0   
44             368            0           7       1                1   
45             369            0           0       0                0   
46             370            0           0       1                0   
47             371            0           9       1                1   
48             372            1          13       0                2   
49             374            0           2       0                0   

    PHQ8_Depressed  PHQ8_Sleep  PHQ8_Tired  PHQ8_Appetite  PHQ8_Failure  \
0                0         0.0           0              0             0   
1                1         1.0           2              2             0   
2                1         1.0           2              2             1   
3                1         0.0 

In [30]:
df.isnull().sum()

Participant_ID        0
PHQ8_Binary           0
PHQ8_Score            0
Gender                0
PHQ8_NoInterest       0
PHQ8_Depressed        0
PHQ8_Sleep            1
PHQ8_Tired            0
PHQ8_Appetite         0
PHQ8_Failure          0
PHQ8_Concentrating    0
PHQ8_Moving           0
dtype: int64

In [31]:
df = df.dropna()

In [32]:
df.isnull().sum()

Participant_ID        0
PHQ8_Binary           0
PHQ8_Score            0
Gender                0
PHQ8_NoInterest       0
PHQ8_Depressed        0
PHQ8_Sleep            0
PHQ8_Tired            0
PHQ8_Appetite         0
PHQ8_Failure          0
PHQ8_Concentrating    0
PHQ8_Moving           0
dtype: int64

In [4]:
df.describe().T

count        mean        std    min    25%    50%    75%  \
Participant_ID      107.0  389.934579  55.187036  303.0  343.5  380.0  439.0   
PHQ8_Binary         107.0    0.280374   0.451296    0.0    0.0    0.0    1.0   
PHQ8_Score          107.0    6.420561   5.463494    0.0    2.0    6.0   10.0   
Gender              107.0    0.588785   0.494370    0.0    0.0    1.0    1.0   
PHQ8_NoInterest     107.0    0.747664   0.825232    0.0    0.0    1.0    1.0   
PHQ8_Depressed      107.0    0.803738   0.873501    0.0    0.0    1.0    1.0   
PHQ8_Sleep          106.0    1.018868   1.004572    0.0    0.0    1.0    2.0   
PHQ8_Tired          107.0    1.037383   0.910372    0.0    0.0    1.0    2.0   
PHQ8_Appetite       107.0    0.915888   1.001146    0.0    0.0    1.0    2.0   
PHQ8_Failure        107.0    0.869159   0.991322    0.0    0.0    1.0    1.0   
PHQ8_Concentrating  107.0    0.700935   0.923641    0.0    0.0    0.0    1.0   
PHQ8_Moving         107.0    0.317757   0.667269    0.0    0.0    0.0    0.0   

                      max  
Participant_ID      491.0  
PHQ8_Binary           1.0  
PHQ8_Score           20.0  
Gender                1.0  
PHQ8_NoInterest       3.0  
PHQ8_Depressed        3.0  
PHQ8_Sleep            3.0  
PHQ8_Tired            3.0  
PHQ8_Appetite         3.0  
PHQ8_Failure          3.0  
PHQ8_Concentrating    3.0  
PHQ8_Moving           3.0

In [33]:
df.shape

(106, 12)

In [34]:
X = df.drop(['Participant_ID','PHQ8_Score', 'PHQ8_Binary', 'Gender'], axis='columns')

In [35]:
y = df.PHQ8_Binary

In [36]:
from sklearn.preprocessing import LabelEncoder
# label encoding

In [37]:
le_PHQ8_NoInterest = LabelEncoder()
le_PHQ8_Depressed = LabelEncoder()
le_PHQ8_Sleep = LabelEncoder()
le_PHQ8_Tired = LabelEncoder()
le_PHQ8_Appetite = LabelEncoder()
le_PHQ8_Failure = LabelEncoder()
le_PHQ8_Concentrating = LabelEncoder()
le_PHQ8_Moving = LabelEncoder()

In [38]:
X['PHQ8_NoInterest_n'] = le_PHQ8_NoInterest.fit_transform(X['PHQ8_NoInterest'])
X['PHQ8_Depressed_n'] = le_PHQ8_Depressed.fit_transform(X['PHQ8_Depressed'])
X['PHQ8_Sleep_n'] = le_PHQ8_Sleep.fit_transform(X['PHQ8_Sleep'])
X['PHQ8_Tired_n'] = le_PHQ8_Tired.fit_transform(X['PHQ8_Tired'])
X['PHQ8_Appetite_n'] = le_PHQ8_Appetite.fit_transform(X['PHQ8_Appetite'])
X['PHQ8_Failure_n'] = le_PHQ8_Failure.fit_transform(X['PHQ8_Failure'])
X['PHQ8_Concentrating_n'] = le_PHQ8_Concentrating.fit_transform(X['PHQ8_Concentrating'])
X['PHQ8_Moving_n'] = le_PHQ8_Moving.fit_transform(X['PHQ8_Moving'])
X.head()


PHQ8_NoInterest  PHQ8_Depressed  PHQ8_Sleep  PHQ8_Tired  PHQ8_Appetite  \
0                0               0         0.0           0              0   
1                0               1         1.0           2              2   
2                0               1         1.0           2              2   
3                1               1         0.0           0              0   
4                0               0         1.0           1              0   

   PHQ8_Failure  PHQ8_Concentrating  PHQ8_Moving  PHQ8_NoInterest_n  \
0             0                   0            0                  0   
1             0                   0            0                  0   
2             1                   0            0                  0   
3             1                   1            0                  1   
4             0                   0            0                  0   

   PHQ8_Depressed_n  PHQ8_Sleep_n  PHQ8_Tired_n  PHQ8_Appetite_n  \
0                 0             0             0                0   
1                 1             1             2                2   
2                 1             1             2                2   
3                 1             0             0                0   
4                 0             1             1                0   

   PHQ8_Failure_n  PHQ8_Concentrating_n  PHQ8_Moving_n  
0               0                     0              0  
1               0                     0              0  
2               1                     0              0  
3               1                     1              0  
4               0                     0              0

In [39]:
X_n = X.drop(['PHQ8_NoInterest', 'PHQ8_Depressed', 'PHQ8_Sleep', 'PHQ8_Tired', 'PHQ8_Appetite', 'PHQ8_Failure', 'PHQ8_Concentrating', 'PHQ8_Moving'], axis = 'columns')
X_n

PHQ8_NoInterest_n  PHQ8_Depressed_n  PHQ8_Sleep_n  PHQ8_Tired_n  \
0                    0                 0             0             0   
1                    0                 1             1             2   
2                    0                 1             1             2   
3                    1                 1             0             0   
4                    0                 0             1             1   
..                 ...               ...           ...           ...   
102                  0                 1             0             0   
103                  1                 1             0             1   
104                  0                 0             0             0   
105                  0                 0             0             0   
106                  1                 1             1             1   

     PHQ8_Appetite_n  PHQ8_Failure_n  PHQ8_Concentrating_n  PHQ8_Moving_n  
0                  0               0                     0              0  
1                  2               0                     0              0  
2                  2               1                     0              0  
3                  0               1                     1              0  
4                  0               0                     0              0  
..               ...             ...                   ...            ...  
102                0               0                     0              1  
103                0               1                     0              0  
104                0               0                     0              0  
105                0               0                     0              0  
106                1               1                     1              1  

[106 rows x 8 columns]

In [40]:
y.tail(100)

6      0
7      0
8      0
9      0
11     1
      ..
102    0
103    0
104    0
105    0
106    0
Name: PHQ8_Binary, Length: 100, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_n, y, test_size=0.30, random_state=101)

In [42]:
from sklearn import tree

In [43]:
model = tree.DecisionTreeClassifier()

In [44]:
model.fit(X_n, y)

DecisionTreeClassifier()

In [45]:
model.score(X_n, y)

1.0

In [46]:
model.predict([[1,1,3,1,2,1,1,1]])

array([1])

In [47]:
model.predict([[1,1,3,1,2,1,0,1]])

array([1])

In [48]:
model.predict([[0,0,3,0,2,1,0,1]])

array([0])

In [49]:
model.predict([[0,0,0,0,0,0,0,0]])

array([0])

In [50]:
model.predict([[3,3,3,3,0,0,0,0]])

array([0])

In [51]:
# tree.plot_tree(model) 

In [52]:
predictions = model.predict(x_test)
predictions

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [53]:
score = model.score(x_test, y_test)
print(score)

1.0
